version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 14 * * MON,WED"
    labels:
      - "dependencies"
      - "edit-on-call"
