name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Run ShellCheck
        run: make lint-scripts
      - name: Install shfmt
        run: sudo snap install shfmt
      - name: Check shell formatting
        run: make check-format

  test-stack:
    needs: lint
    strategy:
      matrix:
        stack: [heroku-22, heroku-24]
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
    - name: run stack test
      run: bash test/test-stack.sh ${{ matrix.stack }}
      env:
        REPO_OWNER: heroku
        REPO_PROJECT: heroku-integration-service-mesh

  test-cnb:
    strategy:
      matrix:
        builder: ["builder:24", "builder:22"]
        arch: ["amd64", "arm64"]
        exclude:
          - builder: "builder:22"
            arch: "arm64"
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    steps:
    - uses: actions/checkout@v7
    - name: Install Pack CLI
      uses: buildpacks/github-actions/setup-pack@e3b14c6e906f91da358e01dc2849ce068188107f # v5.12.5
    - name: Run CNB test
      run: bash test/test-cnb.sh ${{ matrix.builder }} ${{ matrix.arch }}
